### PR TITLE
Refactor generate plots, styling and generating report to separate functions and classes

### LINKED ISSUE #14: Improve gene summary plot for low numbers of genes
When low numbers of genes are included in report the summary plot fits these to width of plot, results in wide bars and looks particularly weird for a single gene with one giant box. Needs inverse scaled padding adding to plot dependent on total number of genes.

### PR DESCRIPTION
**Pull request by jethror1**
Refactored coverage_report_single.py to seperate logic out into smaller functions, now includes 4 extra classes:

- generatePlots( ): functions to generate full gene plots, summary plot and low exon plots
- styleTables( ): separate functions for styling of all tables in report
- calculateValues( ): functions to calculate panel coverage %, snp coverage and snp % totals
- generateReport( ): functions to combine all variables into template and write output report

Moved getData( ) functions to separate load_data.py script

Reduced number of explicit dtypes with add one dict of dtypes as class attribute for all df's

Added list of genes with <90% coverage at threshold to clinical summary text

Fix #14 - summary gene plot with <10 genes has wider margins to stop very wide bar plot

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: 3 of 4 files reviewed, 16 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[bin/coverage_report_single.py, line 102 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCo7761thSYwY_1TdO:-MQCo7776Gbc9yrt1BCE:b-iyvhz2) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L102)):*
> ```Python
>         for gene in genes:
>             # make plot for each gene / exon
> ```

whitespace
___
*[bin/coverage_report_single.py, line 224 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCrlum60b9T_84TQDy:-MQCrlum60b9T_84TQDz:b-iyvhz2) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L224)):*
> ```Python
> 
>         for gene in genes:
> ```

whitespace
___
*[bin/coverage_report_single.py, line 335 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxuc8AokcBcgDnJVn:-MQCxuc94zFcH0y2ugw_:bey9tr2) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L335)):*
> ```Python
>             # convert image to html string and append to one really long
>             # string to insert in report
>             buffer = BytesIO()
> ```

used twice should probably think about making it a function
___
*[bin/coverage_report_single.py, line 401 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxEubDnqkah6WnX9e:-MQCxEubDnqkah6WnX9f:b-gi5ez1) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L401)):*
> ```Python
>         )
> 
>         if "genes100pct" in locals():
> ```

I would have set the variable as None at the top and check if it's not None
___
*[bin/coverage_report_single.py, line 421 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxfTMCnIUVbpf7z3c:-MQCxfTMCnIUVbpf7z3d:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L421)):*
> ```Python
>         plt.xticks(rotation=55, color="#565656")
> 
>         # adjust whole plot marins
> ```

typo
___
*[bin/coverage_report_single.py, line 538 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD-I9hDcRCRH0jx47v:-MQD-I9hDcRCRH0jx47w:b-1qlg1) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L538)):*
> ```Python
>         # rename columns to display properly
>         sub_threshold_stats = sub_threshold_stats.rename(columns={
>             "gene": "Gene",
> ```

could this become an attribute of the object? since you use it twice
___
*[bin/coverage_report_single.py, line 555 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCzacq-ly3y9cE7dYT:-MQCzacq-ly3y9cE7dYU:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L555)):*
> ```Python
>         )
> 
>         # creat slices of sub_threshold stats df to add styling to
> ```

typo
___
*[bin/coverage_report_single.py, line 618 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCzvhSE1CPEWHqk1lo:-MQCzvhSE1CPEWHqk1lp:bx1vrgf) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L618)):*
> ```Python
>             - vals (list): list of min, mean and max strs
>         Returns:
>             -
> ```

emptyness
___
*[bin/coverage_report_single.py, line 631 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD-8YH-HoDODFOijVi:-MQD-8YH-HoDODFOijVj:b86scri) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L631)):*
> ```Python
>         total_stats = total_stats.reindex(self.vals, axis=1)
>         total_stats.reset_index(inplace=True)
>         total_stats.index = np.arange(1, len(total_stats.index) + 1)
> ```

I hates it https://stackoverflow.com/questions/55102806/why-was-the-name-arange-chosen-for-the-numpy-function
___
*[bin/coverage_report_single.py, line 717 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD1Ca-3Y6i705_iMu9:-MQD1Ca-3Y6i705_iMuA:b-qf9l2l) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L717)):*
> ```Python
> 
>     @staticmethod
>     def style_snps_low_cov(snps_low_cov):
> ```

as far as i can tell this method is identical to the one just below
___
*[bin/coverage_report_single.py, line 939 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD3Z1j3SsaKO8Zr-1x:-MQD3Z1j3SsaKO8Zr-1y:b-wxlmna) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L939)):*
> ```Python
>         # turn dfs into BedTools objects
>         bed = bedtools.BedTool.from_dataframe(bedFile)
>         cov = bedtools.BedTool.from_dataframe(coverageFile)
> ```

not used according to VS code
___
*[bin/coverage_report_single.py, line 1168 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD6d9KEKA76zvikwbY:-MQD6d9KEKA76zvikwbZ:b52i37c) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L1168)):*
> ```Python
> 
>         # format threshold val & select threshold columns
>         threshold = str(args.threshold) + "x"
> ```

store it as an attribute for your objects
___
*[bin/coverage_stats_single.py, line 145 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD90P57o8gAlxAX8GR:-MQD90P57o8gAlxAX8GS:b-iyvhz2) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_stats_single.py#L145)):*
> ```Python
> 
>         for gene in genes:
> ```

whitespace
___
*[bin/load_data.py, line 19 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBHWo2mCH15d_6oIW:-MQDBHWo2mCH15d_6oIX:bdxgutn) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L19)):*
> ```Python
>     with open(exon_stats.name) as exon_file:
>         dtypes = {
>             "chrom": str, "exon_start": int, "exon_end": int, "gene": str,
> ```

you use this dict a lot, maybe find a way to have a config?
___
*[bin/load_data.py, line 147 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBcw89SaXw6vnqJ1e:-MQDBcw89SaXw6vnqJ1f:bv9olvj) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L147)):*
> ```Python
> 
>     column = [
>         "gene", "tx", "chrom", "exon", "exon_start", "exon_end",
> ```

yeah definitely have config
___
*[bin/load_data.py, line 163 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBfVy8OuJLqKTOXEI:-MQDBfVy8OuJLqKTOXEJ:b-jvlgxv) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L163)):*
> ```Python
>     # pandas is terrible and forces floats, change back to int
>     dtypes = {
>         'chrom': str,
> ```

so much configs

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: all files reviewed, 16 unresolved discussions (waiting on @jethror1 and @mattgarner)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: all files reviewed, 16 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[bin/coverage_report_single.py, line 102 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCo7761thSYwY_1TdO:-MQDDSDw2ymA-UYeej0O:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L102)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 224 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCrlum60b9T_84TQDy:-MQDDYarEEZauMvqaU96:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L224)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 335 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxuc8AokcBcgDnJVn:-MQDFx093jvqpqs7tTnt:b-ewsz1w) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L335)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

used twice should probably think about making it a function
</blockquote></details>

added new function png2str( )
___
*[bin/coverage_report_single.py, line 401 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxEubDnqkah6WnX9e:-MQDGZeO8MaTmTGnl0F1:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L401)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I would have set the variable as None at the top and check if it's not None
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 421 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCxfTMCnIUVbpf7z3c:-MQDGcJq20EpBp9z0NiD:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L421)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 538 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD-I9hDcRCRH0jx47v:-MQDHrHu6WniS4wwQJ69:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L538)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could this become an attribute of the object? since you use it twice
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 555 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCzacq-ly3y9cE7dYT:-MQDItyf-29oNWCaIJ6o:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L555)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 618 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQCzvhSE1CPEWHqk1lo:-MQDJ2zt4vvGbRFPf0Pb:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L618)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

emptyness
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 631 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD-8YH-HoDODFOijVi:-MQDJHJvAHLsokAa3_ZC:b-u5e9v7) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L631)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I hates it https://stackoverflow.com/questions/55102806/why-was-the-name-arange-chosen-for-the-numpy-function
</blockquote></details>

same but 🤷
___
*[bin/coverage_report_single.py, line 717 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD1Ca-3Y6i705_iMu9:-MQDQi4n-p4_hAMbu7CI:bmk5ckw) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L717)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

as far as i can tell this method is identical to the one just below
</blockquote></details>

it was except for variable names and handling if the df was empty and replacing with text, have made a generalised function then check what is returned to replace with appropriate text
___
*[bin/coverage_report_single.py, line 939 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD3Z1j3SsaKO8Zr-1x:-MQDRZKjEwgB4rZ8-lS8:b-mfvrnz) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L939)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not used according to VS code
</blockquote></details>

https://www.google.com/url?sa=i&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Felection2016-rnc-republican-national-convention-26BRyIYOA3kvL9y0M&psig=AOvVaw2oS6i7kwo4DqXn14h-oy1k&ust=1609867732422000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIie1eTmgu4CFQAAAAAdAAAAABAI

Used at line 1502:
```        # if SNP VCF(s) have been passed
        snps_low_cov, snps_high_cov, snps_no_cov = calculate.snp_coverage(
            args.snps, raw_coverage
        )```
```

___
*[bin/coverage_report_single.py, line 1168 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD6d9KEKA76zvikwbY:-MQDRfwP-qycVvV6P46C:b2irphm) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_report_single.py#L1168)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

store it as an attribute for your objects
</blockquote></details>

have changed to add this to when it is passed with arguments and removed all the ```+ "x"``` throughout
___
*[bin/coverage_stats_single.py, line 145 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQD90P57o8gAlxAX8GR:-MQDS2lR-00vkWobFSUo:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/coverage_stats_single.py#L145)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[bin/load_data.py, line 19 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBHWo2mCH15d_6oIW:-MQDSAGK0lqO7qslVzr4:b1fz9pn) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L19)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you use this dict a lot, maybe find a way to have a config?
</blockquote></details>

hmm maybe
___
*[bin/load_data.py, line 147 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBcw89SaXw6vnqJ1e:-MQDSq8TAcZUUDyX_SzG:b-h7a60) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L147)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

yeah definitely have config
</blockquote></details>

I would but theyre all kinda different
___
*[bin/load_data.py, line 163 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBfVy8OuJLqKTOXEI:-MQDTUQP1bScJGpL9uCQ:bnj7hl0) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L163)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

so much configs
</blockquote></details>

same as above

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: 1 of 4 files reviewed, 16 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[bin/load_data.py, line 19 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBHWo2mCH15d_6oIW:-MQH9PqJEeIzX2nSxioF:b-k7abs6) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

hmm maybe
</blockquote></details>

have changed to class and added dtypes as an attribute, pandas accepts a dict with columns not present in the table so can add one big dict for all
___
*[bin/load_data.py, line 147 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBcw89SaXw6vnqJ1e:-MQH9Jf1EbhhTBGtd1M_:b-v8evcs) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L147)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I would but theyre all kinda different
</blockquote></details>

column names are specific to each table, dtypes have changed

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: all files reviewed, 17 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[bin/coverage_report_single.py, line 505 at r4](https://reviewable.io/reviews/eastgenomics/athena/18#-MRUogDg8GxURb48L6Ga:-MRUogDh4mYnYVpmqunz:b7niqum) ([raw file](https://github.com/eastgenomics/athena/blob/3096671c47d554c4139b2d6199fd83bc3b7f835c/bin/coverage_report_single.py#L505)):*
> ```
> numbner
> ```
typo

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: 3 of 4 files reviewed, 17 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[bin/coverage_report_single.py, line 505 at r4](https://reviewable.io/reviews/eastgenomics/athena/18#-MRUogDg8GxURb48L6Ga:-MRVGM7uAVoF6X99WJ2S:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/3096671c47d554c4139b2d6199fd83bc3b7f835c/bin/coverage_report_single.py#L505)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> numbner
> ```
typo
</blockquote></details>

Done.
___
*[bin/load_data.py, line 163 at r2](https://reviewable.io/reviews/eastgenomics/athena/18#-MQDBfVy8OuJLqKTOXEI:-MRVGE2lETfmBdesUw-N:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/65c821519851d053319e1b2ec5cf36e6a79adb5d/bin/load_data.py#L163)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
