### PR TITLE
Implemented per-chromosome coverage plotting

### PR DESCRIPTION
**Pull request by spaul91**
- Optional per-chromosome coverage plotting added.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)

### CODE REVIEW

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[bin/coverage_report_single.py, line 446 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpC1rMz-7yq_Trx30HC:-MpC1rMz-7yq_Trx30HD:bmqvgdm) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/coverage_report_single.py#L446)):*
> ```Python
> 
>         Args:
>             per_base_coverge: per_base.bed.gz data frame
> ```

To correct

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[bin/coverage_report_single.py, line 457 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCpfkqBiHz0YL8UmRC:-MpCpfkqBiHz0YL8UmRD:b-ur4vuk) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/coverage_report_single.py#L457)):*
> ```Python
> 
>         fig, axs = plt.subplots(
> ```

no need for whitespace between lines, this can just be:
```
fig, axs = plt.subplots(
    figsize=(30, 30), nrows=nrows, ncols=ncols,
    gridspec_kw=dict(hspace=0.5), sharey=sharey
)
```
___
*[bin/coverage_report_single.py, line 458 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpD199u5bCfX7CWZmqe:-MpCpe_d7cTgnxNhA5f2:baypprv) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/coverage_report_single.py#L458)):*
> 
>                 figsize=(30, 30),
> 

any objection to making this wider to better fill the width of the page?
___
*[bin/load_data.py, line 4 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCrgRW4-mOs-iPEh7K:-MpCrgRW4-mOs-iPEh7L:b-qz8yr8) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/load_data.py#L4)):*
> ```Python
> import pandas as pd
> from pathlib import Path
> import re
> ```

unneeded?
___
*[data/templates/single_template.html, line 334 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCwytR3NfK0eMB-M_J:-MpCwytR3NfK0eMB-M_K:b6v8815) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L334)):*
> ```HTML
>                 <h2>Coverage per chromosome</h2> 
>                 <br>
>                 The following section provides an overview of global read coverage per chromosome.
> ```

can you add something here to explain that if capture coverage is being plotted then the displayed plot won't be representative of chromosome level coverage (i.e. the capture regions are adjacent), this will be more important if/when this gets shared with others to use and may expect to see full chromosome level plotting 
___
*[data/templates/single_template.html, line 335 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpD0ghTDiDQMeJf1ihf:-MpD0ghTDiDQMeJf1ihg:bvy5ea4) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L335)):*
> ```HTML
>                 <br>
>                 The following section provides an overview of global read coverage per chromosome.
>                 </br>
> ```

could you either remove this break tag or reduce top padding on the plot as it looks in the example to have quite a big gap to the text above 
___
*[data/templates/single_template.html, line 376 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCrwCPDVCqLSDTx0Sc:-MpCrwCPDVCqLSDTx0Sd:b552oln) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L376)):*
> ```HTML
> 
>     
>     
> ```

I think you have switched the comments on this and the function above

**Comment by jethror1** [comment]
version wants bumping to `1.3.0`: https://github.com/eastgenomics/athena/blob/master/bin/version.py

fixes #53 that I forgot to do last time for `1.2.1`

**Comment by spaul91** [comment]
I'm including a fix to https://github.com/eastgenomics/athena/issues/56 in this PR, so please don't merge this until that's done. Thank you

**Comment by spaul91** [comment]
> I'm including a fix to #56 in this PR, so please don't merge this until that's done. Thank you

Have opened bugfix/issue-56 in an independent branch. Ignore my previous comment

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[bin/coverage_report_single.py, line 458 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpD199u5bCfX7CWZmqe:-MplZ1gyA_OskZNGT74C:b-l6e877) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/coverage_report_single.py#L458)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> 
>                 figsize=(30, 30),
> 

any objection to making this wider to better fill the width of the page?
</blockquote></details>

Done - used matplotlib's constrained layout function instead, as that allowed the plots to occupy the width of the page.
___
*[data/templates/single_template.html, line 334 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCwytR3NfK0eMB-M_J:-MplZEAG2Wq5sDxGsq-J:bb6un1j) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L334)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add something here to explain that if capture coverage is being plotted then the displayed plot won't be representative of chromosome level coverage (i.e. the capture regions are adjacent), this will be more important if/when this gets shared with others to use and may expect to see full chromosome level plotting 
</blockquote></details>

Done
___
*[data/templates/single_template.html, line 335 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpD0ghTDiDQMeJf1ihf:-MplZGdu2KWNbVoBI4bT:b-886gsx) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L335)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you either remove this break tag or reduce top padding on the plot as it looks in the example to have quite a big gap to the text above 
</blockquote></details>

Fixed
___
*[data/templates/single_template.html, line 376 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCrwCPDVCqLSDTx0Sc:-MplZIw28bqPLvctAUuB:b-886gsx) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/data/templates/single_template.html#L376)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think you have switched the comments on this and the function above
</blockquote></details>

Fixed
___
*[bin/load_data.py, line 4 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCrgRW4-mOs-iPEh7K:-MplZO0n6AaAHHSPDbGG:b-xghj2x) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/load_data.py#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

unneeded?
</blockquote></details>

Removed, good catch

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[bin/coverage_report_single.py, line 457 at r1](https://reviewable.io/reviews/eastgenomics/athena/59#-MpCpfkqBiHz0YL8UmRC:-MppyzX16Hv42HI4ua7Z:b-vmaz2m) ([raw file](https://github.com/eastgenomics/athena/blob/c837497463af8e0bab6159ec3e6a5bc8d9e5e878/bin/coverage_report_single.py#L457)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

no need for whitespace between lines, this can just be:
```
fig, axs = plt.subplots(
    figsize=(30, 30), nrows=nrows, ncols=ncols,
    gridspec_kw=dict(hspace=0.5), sharey=sharey
)
```
</blockquote></details>

This has been refactored

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
