### PR TITLE
gene plots panel filter

### LINKED ISSUE #74: Add regex searching to full gene plots
Requires adding the following to `fullPlots` dataTables section config: `{search: {regex: true}`

### PR DESCRIPTION
**Pull request by jethror1**
## Changes

- adds export to csv buttons to all tables
- adds optional drop down list filter to all gene plots to show filtered list of gene panels
- adds regex searching for dataTables - fixes #74 

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)

### CODE REVIEW

**Comment by spaul91** [comment]
*[`bin/coverage_report_single.py` line 1223 at r2](https://reviewable.io/reviews/eastgenomics/athena/77#-NJLHGNOAX5aAe55wzBQ:-NJLHGNOAX5aAe55wzBR:b-f2zokm) ([raw file](https://github.com/eastgenomics/athena/blob/8911b4b85b9d0c83ac18d8fa71bafe2cea09a0e4/bin/coverage_report_single.py#L1223)):*
> ```Python
>         hide_plots = ""
> 
>         if all_plots == "":
> ```

Just wanted some clarification - does the filter string mean, "display only what's specified here", and if it's empty, that means "display nothing"?

**Review by spaul91 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77#-:-NJLIARX5e75E_r0ZgEc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[`bin/coverage_report_single.py` line 1223 at r2](https://reviewable.io/reviews/eastgenomics/athena/77#-NJLHGNOAX5aAe55wzBQ:-NJLI82E3kFN7v-qd6RB:b-69gt9l) ([raw file](https://github.com/eastgenomics/athena/blob/8911b4b85b9d0c83ac18d8fa71bafe2cea09a0e4/bin/coverage_report_single.py#L1223)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Just wanted some clarification - does the filter string mean, "display only what's specified here", and if it's empty, that means "display nothing"?
</blockquote></details>

sorry did a bad job of adding comment there, have now fixed it as I added it to the wrong part.

`all_plots` being an empty string means we want to hide the all whole plot div, the `filter_str` being an empty string means there's no drop down panel filter being set so just hiding that filter part

**Review by mattgarner — APPROVED** [review]
:lgtm:

Merging as Sophie has reviewed but is now on leave

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77#-:-NJds0Ot5Royb3rvn2Wz:b-8otz1q)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spaul91)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spaul91)

**Review by mattgarner — COMMENTED** [review]
> Dismissed @spaul91 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spaul91)

**Review by mattgarner — COMMENTED** [review]
> Dismissed @jethror1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spaul91)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/77)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
