### PR TITLE
1.2 - Change annotation script to Python

### LINKED ISSUE #19: add check for annotated bed
would be good to add a check when annotating the bed file that not genes are lost, the bed file is intersected with exons_nirvana and the transcript columns matched. If any transcript is in the bed but not exons_nirvana this will be omitted and will continue without an error.

### PR DESCRIPTION
**Pull request by jethror1**
- replace `annotate_bed.sh` with rewritten `annotate_bed.py`
- checks added to strip chr prefixes from all input files to stop issues of bedtools not handling mismatched intervals
- checks added for empty files at each stage to make debugging easier
- fixes #19

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[README.md, line 16 at r2](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSO2aIB2e8LQttWUzz:-MdSO2aIB2e8LQttWV--:bykgvlk) ([raw file](https://github.com/eastgenomics/athena/blob/17655d81012725e714b6c1e0f78a2ef1fcbc1d98/README.md#L16)):*
> ```
>  B
> ```
` [B`
___
*[README.md, line 33 at r2](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSOWl6D6yQ6BZOhGRw:-MdSOWl6D6yQ6BZOhGRx:b-quur49) ([raw file](https://github.com/eastgenomics/athena/blob/17655d81012725e714b6c1e0f78a2ef1fcbc1d98/README.md#L33)):*
> ```
> 100% overlap
> ```
Does this require that A entirely overlaps B:
```
-----A=============A-----
------------B====B-------
```
 or that A == B?
```
```
-----A=============A-----
-----B=============B-----
```
```

In both cases overlap of B is 100%

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[README.md, line 16 at r2](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSO2aIB2e8LQttWUzz:-MdSTSnM83EFPX8AluAp:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/17655d81012725e714b6c1e0f78a2ef1fcbc1d98/README.md#L16)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>  B
> ```
` [B`
</blockquote></details>

Done.
___
*[README.md, line 33 at r2](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSOWl6D6yQ6BZOhGRw:-MdSRz5CDvOlTT5k7H-G:blrquhb) ([raw file](https://github.com/eastgenomics/athena/blob/17655d81012725e714b6c1e0f78a2ef1fcbc1d98/README.md#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 100% overlap
> ```
Does this require that A entirely overlaps B:
```
-----A=============A-----
------------B====B-------
```
 or that A == B?
```
```
-----A=============A-----
-----B=============B-----
```
```

In both cases overlap of B is 100%
</blockquote></details>

It requires the 2nd, I _think_ having overlapping regions might still cause problems downstream but I'll have to check. 

The first makes sense (i.e. none reciprocal 100% overlap), so if the panel has larger flanks added than the transcript then it still matches, and the panel coordinates are used to define the coverage selected. I select for matching transcripts so it doesn't matter if it intersects with more here (I don't think). Going to have a think and look further at how coverage is calculated to double check it won't do any funky double counting of bases on overlapping.

Again this probably needs thought about displaying what flank is present, or we just go for it and assume scientists know flanks are present and coordinates might not might match what they initially expect 🤷‍♂️

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[bin/annotate_bed.py, line 172 at r3](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSUABJCqdV2Os0gfXP:-MdSUABJCqdV2Os0gfXQ:b-tcayky) ([raw file](https://github.com/eastgenomics/athena/blob/8586fa6c1c91fcb0ec7bd9bea0100e0f56eaac45/bin/annotate_bed.py#L172)):*
> ```Python
> def main():
>     annotate = annotateBed()
>     load = loadData()
> ```

a  comment on what loadData does?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[README.md, line 43 at r3](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSVtP_5YAUml3e5JHH:-MdSVtP_5YAUml3e5JHI:b2dsfe1) ([raw file](https://github.com/eastgenomics/athena/blob/8586fa6c1c91fcb0ec7bd9bea0100e0f56eaac45/README.md#L43)):*
> ```Markdown
> 
> -t / --transcript_file : Transcript annotation file, contains required gene and exon information. must have ONLY the following 4 columns:
> chromosome, start, end, gene, transcript, exon
> ```

There's more than 4 column names listed ?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

___
*[README.md, line 33 at r2](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSOWl6D6yQ6BZOhGRw:-MdSXUPP9L4E42YG8IWT:b-pusmzd) ([raw file](https://github.com/eastgenomics/athena/blob/17655d81012725e714b6c1e0f78a2ef1fcbc1d98/README.md#L33)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

It requires the 2nd, I _think_ having overlapping regions might still cause problems downstream but I'll have to check. 

The first makes sense (i.e. none reciprocal 100% overlap), so if the panel has larger flanks added than the transcript then it still matches, and the panel coordinates are used to define the coverage selected. I select for matching transcripts so it doesn't matter if it intersects with more here (I don't think). Going to have a think and look further at how coverage is calculated to double check it won't do any funky double counting of bases on overlapping.

Again this probably needs thought about displaying what flank is present, or we just go for it and assume scientists know flanks are present and coordinates might not might match what they initially expect 🤷‍♂️
</blockquote></details>

So further down shouldn't cause an issue since it loops over the annotated bed and takes each exon of each gene individually, so even if the same bases were present in adjacent exons with overlapping flanks they wouldn't get counted twice in calculating coverage of _that_ exon.

I think what is needed is to use `-F=1.0`, which is 100% overlap on B where file A is the bed file and file B is exons nirvana.

Example of doing this (p_* is panel bed file, t_* is from exons nirvana), where panel has 5 bp flank greater:
```     
p_chrom   p_start     p_end p_transcript  t_chrom   t_start     t_end t_gene t_transcript  t_exon
0           1  17345365  17345463  NM_003000.2        1  17345370  17345458   SDHB  NM_003000.2       8
1           1  17349092  17349235  NM_003000.2        1  17349097  17349230   SDHB  NM_003000.2       7
2           1  17350457  17350579  NM_003000.2        1  17350462  17350574   SDHB  NM_003000.2       6
3           1  17354233  17354370  NM_003000.2        1  17354238  17354365   SDHB  NM_003000.2       5
4           1  17355084  17355241  NM_003000.2        1  17355089  17355236   SDHB  NM_003000.2       4
```
___
*[README.md, line 43 at r3](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSVtP_5YAUml3e5JHH:-MdSXImy6FIjMjvNlEgI:b7h5bk6) ([raw file](https://github.com/eastgenomics/athena/blob/8586fa6c1c91fcb0ec7bd9bea0100e0f56eaac45/README.md#L43)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

There's more than 4 column names listed ?
</blockquote></details>

I'm dumb and copy pasted but not very well, fixed it

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[bin/annotate_bed.py, line 172 at r3](https://reviewable.io/reviews/eastgenomics/athena/40#-MdSUABJCqdV2Os0gfXP:-MdSYr2-An0JJ6nvo0NM:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/8586fa6c1c91fcb0ec7bd9bea0100e0f56eaac45/bin/annotate_bed.py#L172)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

a  comment on what loadData does?
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
