### PR TITLE
1.2 - Modify gene plots

### PR DESCRIPTION
**Pull request by jethror1**
- changes to add full gene plots to datatables container
- allows for searching and scrolling in fixed window
- deferred rendering enable hundreds of plots in report and only renders first 3 on initial load => doesn't break on big panels
- reduced file size of each plot by ~60% through dropping dpi and making plots transparent
- example report at bottom of page here: https://cuhbioinformatics.atlassian.net/wiki/spaces/P/pages/2216230925/Development

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[data/templates/single_template.html, line 153 at r2](https://reviewable.io/reviews/eastgenomics/athena/34#-MdIW4PqDlie23ge4un1:-MdIW4Pr3qzrDApN4jtu:b-hnzw9s) ([raw file](https://github.com/eastgenomics/athena/blob/a301f506781721696aede5e9da0d012ca1c877c9/data/templates/single_template.html#L153)):*
> ```
> ········
> ```
Whitespace
___
*[data/templates/single_template.html, line 247 at r2](https://reviewable.io/reviews/eastgenomics/athena/34#-MdIW7jTA4gjCeUPJN8A:-MdIW7jTA4gjCeUPJN8B:b-hnzw9s) ([raw file](https://github.com/eastgenomics/athena/blob/a301f506781721696aede5e9da0d012ca1c877c9/data/templates/single_template.html#L247)):*
> ```
> ········
> ```
Whitespace

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[data/templates/single_template.html, line 153 at r2](https://reviewable.io/reviews/eastgenomics/athena/34#-MdIW4PqDlie23ge4un1:-MdIYrYr-LJ2rU5W2oa7:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a301f506781721696aede5e9da0d012ca1c877c9/data/templates/single_template.html#L153)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ········
> ```
Whitespace
</blockquote></details>

Done.
___
*[data/templates/single_template.html, line 247 at r2](https://reviewable.io/reviews/eastgenomics/athena/34#-MdIW7jTA4gjCeUPJN8A:-MdIYryK9M_2DU_GYl6d:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a301f506781721696aede5e9da0d012ca1c877c9/data/templates/single_template.html#L247)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ········
> ```
Whitespace
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
