### PR TITLE
1.2 add gene % to summary text

### LINKED ISSUE #28: Include absolute coverage values for genes in suboptimal coverage list of html report
e.g.
```
Genes with coverage at 20x less than 90%: ARPC1B (NM_005720.3); FYB1 (NM_001465.4); MPIG6B (NM_025260.3); SLFN14 (NM_001129820.1); TPM4 (NM_001145160.1).
```
would become
```
Genes with coverage at 20x less than 90%: ARPC1B (NM_005720.3) 89.9%; FYB1 (NM_001465.4) 50.1%; MPIG6B (NM_025260.3) 10.6%; SLFN14 (NM_001129820.1) 0.1%; TPM4 (NM_001145160.1) 0.0%.
```

(There might be a better way to present this than the format suggested above)

### PR DESCRIPTION
**Pull request by jethror1**
- Adds gene coverage % to clinical summary text
- Fixes #28

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/31)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/31)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[bin/coverage_report_single.py, line 1093 at r2](https://reviewable.io/reviews/eastgenomics/athena/31#-MdM7laODg76N5xfCxA0:-MdM7laP4uCdyhuRvkwu:btccjlg) ([raw file](https://github.com/eastgenomics/athena/blob/7e07826b72d3484d72d9d4ac5e69d95ddbf80df8/bin/coverage_report_single.py#L1093)):*
> ```Python
>                     f'{gene["gene"]} ({gene["tx"]}) '
>                     f'{math.floor(gene[self.threshold] * 100)/100.0}%; '
>                 )
> ```

Does math.floor correctly round numbers up? It seems to round it down even at 0.399 for example.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/31)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @mattgarner)

___
*[bin/coverage_report_single.py, line 1093 at r2](https://reviewable.io/reviews/eastgenomics/athena/31#-MdM7laODg76N5xfCxA0:-MdMBDjV8h21KwSb4TxM:bbr5a5e) ([raw file](https://github.com/eastgenomics/athena/blob/7e07826b72d3484d72d9d4ac5e69d95ddbf80df8/bin/coverage_report_single.py#L1093)):*
Yeah this was intentional, the column selected has coverage as a %. For this summary text we want to round to 2 dp so we round down to not call something 100% when it isn't (i.e. 99.99 ≠ 100). For every other case we decided 2dp precision was acceptable:

```
>>> math.floor(99.9999 * 100) / 100
99.99

>>> math.floor(67.56787 * 100) / 100
67.56

>>> math.floor(0.399 * 100) / 100
0.39

```

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
