### PR TITLE
v1.6.1

### PR DESCRIPTION
**Pull request by growland2**
Add in option to output summary to .txt, fix make/build process by moving .whl's into repo and building/installing from these.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93)

### CODE REVIEW

**Comment by growland2** [comment]
Successful job outputting summary file  https://platform.dnanexus.com/panx/projects/GkG4qBj43y4KbVkB6KBBv5kk/monitor/job/GkGpPfj43y4Kzx9BzgVXkJg3

**Review by jethror1 — COMMENTED** [review]
> Reviewed 15 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93)* status: 15 of 22 files reviewed, all discussions resolved

**Review by jethror1 — CHANGES_REQUESTED** [review]
have you missed pushing changes to the bash script? They don't seem to be included

> Reviewed 1 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93#-:-NzDMgqYCqHaedlDFbsj:bz1ufng)* status: 16 of 22 files reviewed, 4 unresolved discussions (waiting on @growland2)

___
*[`README.md` line 123 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDLJ5r3QqKZWHnXQit:-NzDLJ5r3QqKZWHnXQiu:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/README.md#L123)):*
> ```Markdown
> --panel_filters: preset filters of genes / transcripts to set for the full gene plots, these will be presented in a drop down menu for filtering the plots. These should be passed as key:value pairs of panel  name to display in the drop down and a comma separated list of gene symbols to filter with (i.e. panel1:gene1,gene2,gene3...) (optional)
> --cores: Number of CPU cores to utilise, for larger numbers of genes this will drastically reduce run time. If not given will use maximum available
> --sumary_file: boolean flag to output clinical report summary to a text file (optional; default False)
> ```

typo



_Code quote:_
```Markdown
sumary
```
___
*[`dnanexus/dxapp.json` line 175 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDM9cw2_PRuH6UVwNm:-NzDM9cw2_PRuH6UVwNn:b1hl8bt) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/dxapp.json#L175)):*
> ```JSON
>       "label": "Summary text",
>       "class": "file",
>       "patterns": [
> ```

I think you will also need `optional: true` for this output since it won't always be output, have you runa. test job with `--summary_file=false`?
___
*[`dnanexus/dxapp.json` line 178 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDM2Vj8XNmilIpoq1f:-NzDM2Vj8XNmilIpoq1g:b5k8opi) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/dxapp.json#L178)):*
> ```JSON
>         "*"
>       ],
>       "help": ""
> ```

can you add here what is in this file and that `--summary_file` controls its output



_Code quote:_
```JSON
"help": ""
```
___
*[`dnanexus/readme.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDMQrC9DktxFJ_5IR5:-NzDMQrC9DktxFJ_5IR6:b2nhp9o) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/readme.md#L19)):*
> ```Markdown
> ## Building the app
> 
> The source code for the app is in the `dnanexus/` directory, and may be built from the included makefile. This is will set up the app structure locally in a temporary directory with required dependencies, build the app to the platform and then clear the temp directory. This dependencies listed in requirements.txt
> ```

The



_Code quote:_
```Markdown
This
```

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93)* status: 16 of 22 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`dnanexus/dxapp.json` line 175 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDM9cw2_PRuH6UVwNm:-NzDPIhCCfuiLha4ekd7:bbgp5sl) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/dxapp.json#L175)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think you will also need `optional: true` for this output since it won't always be output, have you runa. test job with `--summary_file=false`?
</blockquote></details>

`optional: true` added, and I will run said job once changes have been pushed
___
*[`dnanexus/dxapp.json` line 178 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDM2Vj8XNmilIpoq1f:-NzDQQOrEzy_jFEZDzzi:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/dxapp.json#L178)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add here what is in this file and that `--summary_file` controls its output
</blockquote></details>

Done.
___
*[`dnanexus/readme.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDMQrC9DktxFJ_5IR5:-NzDQX9-9CUYg97KCOhH:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/readme.md#L19)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

The
</blockquote></details>

Done.

**Review by growland2 — COMMENTED** [review]
changes for eggd_athena.sh are at the bottom of this page

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93#-:-NzDRFh95X-ShV2qAZJE:bjmxbis)* status: 16 of 22 files reviewed, 3 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — CHANGES_REQUESTED** [review]
how strange

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93#-:-NzDSDR89g9_anDJhfnX:b-sf58qh)* status: 16 of 22 files reviewed, 4 unresolved discussions (waiting on @growland2)

___
*[`dnanexus/src/eggd_athena.sh` line 119 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDS9N129C-4tmfjvm0:-NzDS9N27jKpWwjkEmBn:b-7kk2oi) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/src/eggd_athena.sh#L119)):*
> ```Shell
>     report=$(dx upload $report --brief)
>     annotated_bed=$(dx upload $annotated_bed_gz --brief)
>     summary_text=$(dx upload $summary_text --brief)
> ```

does this not need to be conditional?



_Code quote:_
```Shell
summary_text=$(dx upload $summary_text --brief)
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @growland2)

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`dnanexus/src/eggd_athena.sh` line 119 at r1](https://reviewable.io/reviews/eastgenomics/athena/93#-NzDS9N129C-4tmfjvm0:-NzDWg7V9UYfb4nFiHx7:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/b34fa1e4752f15b2df5f8ae906d018ad24747dba/dnanexus/src/eggd_athena.sh#L119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this not need to be conditional?
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 22 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/93#-:-NzDYd2_9GX6TCnI7ykf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
