### PR TITLE
1.2 - Modify sub-threshold plots

### LINKED ISSUE #2: change layout of subplot grid for small number of plots
Hard coded to 4 columns, with only a few plots this could be a 1x2 / 2x2 grid etc. to make plots fill the report width

### PR DESCRIPTION
**Pull request by jethror1**
- Rewritten how plots of exon with coverage beneath threshold are generated
- Coverage values and coordinates for each plot then passed in an array to template, where dataTables + plotly are used to generate the plots in a dataTable window
- Reduced plot file size from <1MB per plot to ~4KB
- Deferred rendering and pagination now allow the reports to handle hundreds of plots without crashing and no impact on initial load time
- Example output may be found at bottom of page here: https://cuhbioinformatics.atlassian.net/wiki/spaces/P/pages/2216230925/Development
- Fixes #2 #24

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/athena/36)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/36)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[data/templates/single_template.html, line 162 at r2](https://reviewable.io/reviews/eastgenomics/athena/36#-MdIiv82-cnr1HeQg5mv:-MdIiv839jL_BPNG48Rk:b-8gkoxs) ([raw file](https://github.com/eastgenomics/athena/blob/33ea0b01cbd5f2596545127eeee2ef88c14d9e54/data/templates/single_template.html#L162)):*
> ```
> ··········
> ```
Whitespace

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/36)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[data/templates/single_template.html, line 162 at r2](https://reviewable.io/reviews/eastgenomics/athena/36#-MdIiv82-cnr1HeQg5mv:-MdIkdVMD0fKIyhcyerv:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/33ea0b01cbd5f2596545127eeee2ef88c14d9e54/data/templates/single_template.html#L162)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ··········
> ```
Whitespace
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
